### ISSUE TITLE
✨ Rogue-Lite Meta Progression

### ISSUE THREAD

**Issue by NathanThus** [Rogue-Ape-Studios/Crusader#278]
- [x] ✨ In-game Currency
- [x] ✨ Shop UI
- [x] ✨ Shop Functionality
- [x] ✨ Base Player Stats
- [x] ✨ Tiered Upgrades
- [x] ✨ Ability to Respec
- [ ] ✨ Player Stat Overview
- [x] ✨ Save System

**Comment by davey2206** [comment]
![Image](https://github.com/Rogue-Ape-Studios/Crusader/assets/39116329/a85934a9-2939-4ec8-b45e-95182f56db9c)
